language: node_js
node_js:
  - '6'
before_install:
  - npm install -g typescript typings gulp-cli istanbul jasmine-core
  - typings install
script:
  - npm test
after_script:
  - npm install coveralls@2 && cat ./coverage/lcov.info | coveralls